import React from 'react';
import logo from '../../images/Logo.svg';

export default function About() {
  return (
    <section className="about">
      <img
        className="about__logo about__animation"
        src={logo}
        alt="Mantika logo"
      />
      <h1 className="about__title about__animation">About us</h1>
      <h2 className="about__subtitle about__animation">
        Mantika is a space from creators to creators.
      </h2>
      <h3 className="about__paragraph-subtitle about__animation">
        Why Mantika?
      </h3>
      <p className="about__paragraph about__animation">
        The italian philosopher Giorgio Colli revisit the famous duality
        generated by Nietzsche in The brirth of the tragedy: Apollo and Dionysus
        as the origin of the creative thinking. In Colli's view, both gods, both
        ways of creative thinking are really similar: to connect with the
        divinity, one needs to enter an extatic state: the bacchae for Dionysus
        and the pythoness fo Apollo.
      </p>
      <p className="about__paragraph about__animation">
        Both women had to ingest psychedelic substances to enter this state,
        both had to nulify some kind of their identity to have a relationship
        with the divine. This was called, in Dionysus case mania, and in
        Apollo's mantica. But for Colli, both of them are the proof of a
        profound bond between the two origins of the creative thinking.
      </p>
      <h3 className="about__paragraph-subtitle about__animation">
        Why Mantika?
      </h3>
      <p className="about__paragraph about__animation">
        We think the divine as a relationship of the humane with the reallity
        beyond the rational thinking. It's really possible that the bacchae and
        the pythoness were women becouse the divine implies the capacity of
        creation, and: what's more divine that the capacity to create life? To
        end this text about philosophy, Colli abstracts the bond between Apollo
        and Dionysus in the myth of the Cretan Labyrinth, here, the suality of
        both gods, their cruelty, is mixed with the humanity and with the space:
        Ariadne has the solution to the labyrinth in her dance, the creative
        movement guides Theseus within the creative walls to find the monster.
      </p>
      <p className="about__paragraph about__animation">
        We're Mantika, a place to solidify and create new relationships between
        the artistic and creative comunnity.
      </p>
    </section>
  );
}
